pipeline {
    agent any
    
    environment {
        MONGODB_URI = 'mongodb+srv://mrsmithz:123456Za@cluster0.fydss.mongodb.net/Dockie-dev'
        PORT = 8000
    }

    stages {
        stage('Pull code from branch main') {
            steps {
                git branch: 'main', url: 'https://github.com/Mrsmithz/Project-SW-Dev-and-Env.git'
            }
        }
        stage('Download dependency') {
            steps {
                dir('backend') {
                    sh 'npm install'
                }
            }
        }
        stage('Run unit test') {
            steps {
                dir('backend') {
                    sh 'npm run test'
                }
            }
        }
        stage('Create unit test report') {
            steps {
                dir('backend') {
                    script {
                        if (!fileExists('reports')) {
                            sh 'mkdir reports'
                        }
                    }
                    sh 'npm run test 2> reports/unit.txt'
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'reports', reportFiles: 'unit.txt', reportName: 'Unit Test Report', reportTitles: 'Unit Test Report'])
                }
            }
        }
        stage('Create unit test coverage report') {
            steps {
                dir('backend') {
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'coverage/lcov-report', reportFiles: 'index.html', reportName: 'Unit Test Coverage Report', reportTitles: 'Unit Test Coverage Report'])
                }
            }
        }
        stage('deploy') {
            steps {
                dir('backend') {
                    sshagent(credentials: ['dockie-ssh']) {
                        sh 'ssh -o StrictHostKeyChecking=no mrsmithz@188.166.185.128 uptime'
                        sh 'ssh -v mrsmithz@188.166.185.128'
                        sh """
                            ssh -v mrsmithz@188.166.185.128 << EOF
                            cd app/Project-SW-Dev-and-Env/
                            git pull
                            cd deployment/
                            docker-compose up -d --build express-app
                            exit
                        EOF"""
                    }
                }
            }
        }
    }
}