services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf:/etc/nginx
  next-app:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
  express-app:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: on-failure